### PR TITLE
Update powering-pypi.md

### PR DESCRIPTION
**Pull request by di**
Add a link to the 2021 update

### CODE REVIEW

**Comment by dstufft** [comment]
Oh no, now I have to remember how to publish my blog. I'll try to get to this this weekend!

**Comment by di** [comment]
Maybe this?
https://github.com/dstufft/caremad.io/blob/a59905c77843942fd6ee4d394afcecc5d28983ac/Makefile#L16-L17

Also, lol:
https://github.com/dstufft/caremad.io/blob/a59905c77843942fd6ee4d394afcecc5d28983ac/Makefile#L1

**Comment by dstufft** [comment]
Computers are bad and deserve our scorn and to be called names.

**Comment by dstufft** [comment]
Looks like I got it working locally again, merging and deploying.

**Pull request merged**
